### ISSUE TITLE
help

### ISSUE THREAD

**Issue by clq12** [satisfactorymodding/SatisfactoryModLoader#144]
Error
Unexpected error while downloading file https://github.com/satisfactorymodding/SatisfactoryModLoader/releases/download/3.4.0/SML.zip: unable to verify the first certificate. Trace:
RequestError: unable to verify the first certificate
at ClientRequest.<anonymous> (file:///C:/Users/23125/AppData/Local/Programs/Satisfactory%20Mod%20Manager/resources/app.asar/dist/electron/renderer.js:197:106039)
at Object.onceWrapper (node:events:514:26)
at ClientRequest.emit (node:events:406:35)
at ClientRequest.t.emit (file:///C:/Users/23125/AppData/Local/Programs/Satisfactory%20Mod%20Manager/resources/app.asar/dist/electron/renderer.js:197:75515)
at TLSSocket.socketErrorListener (node:_http_client:447:9)
at TLSSocket.emit (node:events:394:28)
at emitErrorNT (node:internal/streams/destroy:157:8)
at emitErrorCloseNT (node:internal/streams/destroy:122:3)
at processTicksAndRejections (node:internal/process/task_queues:83:21)
at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
at TLSSocket.emit (node:events:394:28)
at TLSSocket._finishInit (node:_tls_wrap:944:8)
at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)
Seems wrong? Generate debug info and send it together with this error message
over on the modding discord in #help-using-mods

**Comment by clq12** [comment]
This problem has occurred many times，and i never install mod ,but i want use mod,so what can i do

**Comment by AstroFloof** [comment]
This is not an issue related to SML itself, and is SMM's fault. Please come to the Discord so we can help you debug your issue further. 
https://discord.gg/TShj39G
